module Parser exposing (TranscriptLine, parseTranscriptionXML)

import Combine
    exposing
        ( (*>)
        , (<*)
        , ParseErr
        , ParseOk
        , Parser
        , andMap
        , between
        , fail
        , many
        , manyTill
        , map
        , optional
        , or
        , parse
        , regex
        , skip
        , string
        , whitespace
        )
import Combine.Num exposing (int)
import Regex


type alias TranscriptLine =
    { time : Int
    , content : String
    }


parseTranscriptionXML : String -> Result (ParseErr ()) (ParseOk () (List TranscriptLine))
parseTranscriptionXML transcription =
    parse transcriptionXML (noWhitespace transcription)


noWhitespace : String -> String
noWhitespace string =
    Regex.replace Regex.All (Regex.regex "\n") (\_ -> " ") string


transcriptionXML : Parser state (List TranscriptLine)
transcriptionXML =
    or userGeneratedTrascript autoGeneratedTranscript


userGeneratedTrascript : Parser state (List TranscriptLine)
userGeneratedTrascript =
    openingTag "?xml"
        *> openingTag "timedtext"
        *> openingTag "body"
        *> many (line userGeneratedLine)
        <* closingTag "body"
        <* closingTag "timedtext"


autoGeneratedTranscript : Parser state (List TranscriptLine)
autoGeneratedTranscript =
    openingTag "?xml"
        *> openingTag "timedtext"
        *> head
        *> openingTag "body"
        *> selfClosingTag "w"
        *> many (line autoGeneratedLine)
        <* closingTag "body"
        <* closingTag "timedtext"


head : Parser state (List String)
head =
    openingTag "head" *> manyTill anyCharacter (closingTag "head")


line : Parser state String -> Parser state TranscriptLine
line lineParser =
    time
        |> map buildTranscriptLine
        |> andMap lineParser


buildTranscriptLine : Int -> String -> TranscriptLine
buildTranscriptLine time content =
    { time = time, content = content }


time : Parser state Int
time =
    string "<p t=\"" *> int <* manyTill anyCharacter (string ">")


userGeneratedLine : Parser state String
userGeneratedLine =
    manyTill anyCharacter (closingTag "p")
        |> formatLine

autoGeneratedLine : Parser state String
autoGeneratedLine =
    manyTill word (or emptyLine (closingTag "p"))
        |> formatLine


formatLine : Parser state (List String) -> Parser state String
formatLine parser =
    parser
        |> map (String.join "")
        |> map (Regex.replace Regex.All (Regex.regex "&#39;") (\_ -> "'"))
        |> map (Regex.replace Regex.All (Regex.regex "&quot;") (\_ -> "\""))


anyCharacter : Parser state String
anyCharacter =
    regex "."


word : Parser state String
word =
    openingTag "s"
        *> manyTill anyCharacter (closingTag "s")
        |> map (String.join "")


emptyLine : Parser state String
emptyLine =
    whitespace *> string "</p>" <* whitespace


openingTag : String -> Parser state (List String)
openingTag name =
    whitespace *> string ("<" ++ name) *> manyTill anyCharacter (string ">")


closingTag : String -> Parser state String
closingTag name =
    string ("</" ++ name ++ ">") <* whitespace


selfClosingTag : String -> Parser state (List String)
selfClosingTag name =
    whitespace *> string ("<" ++ name) *> manyTill anyCharacter (string "/>") <* whitespace
